export type Page = 
  | "dashboard" 
  | "contracts" 
  | "tender-ai" 
  | "review" 
  | "library" 
  | "risk" 
  | "renewals" 
  | "audit" 
  | "admin" 
  | "managers" 
  | "calendar" 
  | "settings"
  | "requests" 
  | "generate" 
  | "negotiate" 
  | "approval" 
  | "execute" 
  | "search" 
  | "comply" 
  | "exit" 
  | "vendors" 
  | "analytics";

